export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';